Se 2769
DBCDK/ess-payara pull request #1
Opened 2019-11-15 11:43 UTC by noah-dbc

2019-11-19 10:29 UTC, thpdbc commented on pom.xml
>  </project>
Man kan muligvis blive fri fra Javadoc advarsler for genereret kode
(https://is.dbc.dk/job/ess-payara/job/SE-2769/8/analysis/)
ved at tilføje:
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <version>2.9.1</version>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <excludePackageNames>dk.dbc.openformat,dk.dbc.sru</excludePackageNames>
                </configuration>
            </plugin>
        </plugins>

2019-11-19 11:28 UTC, thpdbc commented on service/src/main/java/dk/dbc/ess/service/ExternalSearchService.java
> +                "; start: " + start + "; rows: " + rows +
Log framework ​slf4j
understøtter også formatering så man kan laves det med:
```
        log.info("base: {}; format: {}; start: {}; rows: {}; trackingId: {}; query: {}; type: {}",
                base, format, start, rows, trackingId, query, (isRPN ? "rpn" : "cql"));
```
Hvis man bruger det undergår man konkatenere strengen, hvis log er slået fra. Formateringen bliver ikke kaldt hvis loglevel er sat så skal printes

2019-11-19 12:05 UTC, thpdbc approved these changes

2019-11-26 09:20 UTC, mb-dbc-dk requested changes
Lets take a look together

2019-11-26 09:20 UTC, mb-dbc-dk commented on pom.xml
>      </properties>
parent from:

    <repositories>
        <repository>
            <id>mavenrepo.dbc.dk</id>
            <url>http://mavenrepo.dbc.dk/content/groups/public</url>
        </repository>
    </repositories>

    <parent>
        <groupId>dk.dbc</groupId>
        <artifactId>microservice-pom</artifactId>
        <version>latest-SNAPSHOT</version>
        <relativePath/>
    </parent>

2019-11-26 09:20 UTC, mb-dbc-dk commented on pom.xml
> +
Inherited from microservice-pom

2019-11-26 09:20 UTC, mb-dbc-dk commented on service/src/main/java/dk/dbc/ess/service/ExternalSearchService.java
> +    @Path("rpn/")
Trailing /

2019-11-26 09:20 UTC, mb-dbc-dk commented on service/src/main/java/dk/dbc/ess/service/HowRU.java
> +
Bean should be either: \@Stateless or \@Singleton

Pretty sure as is won't work as expected in payara
Will try default constructor to make an instance where howru can be called hence no health checks performed. (no checks implemented?)

2019-11-26 09:20 UTC, mb-dbc-dk commented on service/src/main/java/dk/dbc/ess/service/ExternalSearchService.java
> +    private static final Logger log = LoggerFactory.getLogger(ExternalSearchService.class);
Should be \@Stateless To have working CDI

2019-11-26 09:20 UTC, mb-dbc-dk commented on service/src/main/java/dk/dbc/ess/service/ExternalSearchService.java
> +        this.client = settings.getClientBuilder().build();
Beans have (void) constructors. Configuration needs to be \@Inject'ed. If you need to initialize you can do it in a \@PostConstruct annotaed public void method.

2019-11-26 09:20 UTC, mb-dbc-dk commented on service/src/main/java/dk/dbc/ess/service/EssConfiguration.java
> +        }
Put this in the \@PostConstruct

2019-11-26 09:20 UTC, mb-dbc-dk commented on service/src/main/java/dk/dbc/ess/service/EssConfiguration.java
> +        return clientBuilder;
No need to store clientbuilder - only called once

2019-11-27 06:31 UTC, mb-dbc-dk commented on service/src/main/java/dk/dbc/ess/service/HowRU.java
> +        return false;
A little log about which service didn't respond will facilitate faster service debug

2019-11-27 06:33 UTC, mb-dbc-dk approved these changes
Just a little more log

2019-11-27 09:59 UTC, merged

2019-11-27 11:30 UTC, thpdbc commented on pom.xml
>  </project>
Kiggede lige igen på javadoc warnings for https://is.dbc.dk/job/ess-payara/job/master/21/

Konfigurations af maven-javadoc-plugin skal stå i projekt rod pom.xml, fordi det bliver kørt med "mvn javadoc:aggregate" i rod folderen

excludePackageNames skal være "dk.dbc.openformat,dk.dbc.sru.*", fordi openformat klassene ligger i dk.dbc.openformat pakken, men dk.dbc.sru klasserne ligger i subdirectories *